### ISSUE TITLE
TSPLib importer issue tracker

### ISSUE THREAD

**Issue by jkinable** [jgrapht/jgrapht#1067]
During the last testing, some problems in the TSPLib importer surfaced. This issue is meant to track the progress on the TSPLib implementation. PR #1060 identified a number of instances where the TSPLib importer failed. Goal is to have full support for all TSPLib instances. Currently, instances which have a `EDGE_WEIGHT_SECTION` instead of a `NODE_COORD_SECTION` are not yet supported. In issue #1064 a separate problem is raised which seems to indicate that the edge weights are not correctly calculated.

```
Test a280.tsp.gz
Test ali535.tsp.gz
Test att48.tsp.gz
Test att532.tsp.gz
Test bayg29.tsp.gz
Failed : Instance bayg29.tsp.gz - vertexSet expected 29 and read 0
Test bays29.tsp.gz
Failed : Instance bays29.tsp.gz - vertexSet expected 29 and read 0
Test berlin52.tsp.gz
Test bier127.tsp.gz
Test brazil58.tsp.gz
Failed : Instance brazil58.tsp.gz - vertexSet expected 58 and read 0
Skip test brd14051.tsp.gz (too large)
Test brg180.tsp.gz
Failed : Instance brg180.tsp.gz - vertexSet expected 180 and read 0
Test burma14.tsp.gz
Test ch130.tsp.gz
Test ch150.tsp.gz
Test d1291.tsp.gz
Skip test d15112.tsp.gz (too large)
Test d1655.tsp.gz
Skip test d18512.tsp.gz (too large)
Test d198.tsp.gz
Skip test d2103.tsp.gz (too large)
Test d493.tsp.gz
Test d657.tsp.gz
Test dantzig42.tsp.gz
Failed : Instance dantzig42.tsp.gz - vertexSet expected 42 and read 0
Test dsj1000.tsp.gz
Test eil101.tsp.gz
Test eil51.tsp.gz
Test eil76.tsp.gz
Test fl1400.tsp.gz
Test fl1577.tsp.gz
Skip test fl3795.tsp.gz (too large)
Test fl417.tsp.gz
Skip test fnl4461.tsp.gz (too large)
Test fri26.tsp.gz
Failed : Instance fri26.tsp.gz - vertexSet expected 26 and read 0
Test gil262.tsp.gz
Test gr120.tsp.gz
Failed : Instance gr120.tsp.gz - vertexSet expected 120 and read 0
Test gr137.tsp.gz
Test gr17.tsp.gz
Failed : Instance gr17.tsp.gz - vertexSet expected 17 and read 0
Test gr202.tsp.gz
Test gr21.tsp.gz
Failed : Instance gr21.tsp.gz - vertexSet expected 21 and read 0
Test gr229.tsp.gz
Test gr24.tsp.gz
Failed : Instance gr24.tsp.gz - vertexSet expected 24 and read 0
Test gr431.tsp.gz
Test gr48.tsp.gz
Failed : Instance gr48.tsp.gz - vertexSet expected 48 and read 0
Test gr666.tsp.gz
Test gr96.tsp.gz
Test hk48.tsp.gz
Failed : Instance hk48.tsp.gz - vertexSet expected 48 and read 0
Test kroA100.tsp.gz
Test kroA150.tsp.gz
Test kroA200.tsp.gz
Test kroB100.tsp.gz
Test kroB150.tsp.gz
Test kroB200.tsp.gz
Test kroC100.tsp.gz
Test kroD100.tsp.gz
Test kroE100.tsp.gz
Test lin105.tsp.gz
Test lin318.tsp.gz
Test linhp318.tsp.gz
Test nrw1379.tsp.gz
Test p654.tsp.gz
Test pa561.tsp.gz
Failed : Instance pa561.tsp.gz - vertexSet expected 561 and read 0
Test pcb1173.tsp.gz
Skip test pcb3038.tsp.gz (too large)
Test pcb442.tsp.gz
Skip test pla33810.tsp.gz (too large)
Skip test pla7397.tsp.gz (too large)
Skip test pla85900.tsp.gz (too large)
Test pr1002.tsp.gz
Test pr107.tsp.gz
Test pr124.tsp.gz
Test pr136.tsp.gz
Test pr144.tsp.gz
Test pr152.tsp.gz
Test pr226.tsp.gz
Skip test pr2392.tsp.gz (too large)
Test pr264.tsp.gz
Test pr299.tsp.gz
Test pr439.tsp.gz
Test pr76.tsp.gz
Test rat195.tsp.gz
Test rat575.tsp.gz
Test rat783.tsp.gz
Test rat99.tsp.gz
Test rd100.tsp.gz
Test rd400.tsp.gz
Skip test rl11849.tsp.gz (too large)
Test rl1304.tsp.gz
Test rl1323.tsp.gz
Test rl1889.tsp.gz
Skip test rl5915.tsp.gz (too large)
Skip test rl5934.tsp.gz (too large)
Test si1032.tsp.gz
Failed : Failed to import graph from TSPLIB-file: Invalid TYPE value <TSP (M.~Hofmeister)>
Test si175.tsp.gz
Failed : Failed to import graph from TSPLIB-file: Invalid TYPE value <TSP (M.~Hofmeister)>
Test si535.tsp.gz
Failed : Failed to import graph from TSPLIB-file: Invalid TYPE value <TSP (M.~Hofmeister)>
Test st70.tsp.gz
Test swiss42.tsp.gz
Failed : Instance swiss42.tsp.gz - vertexSet expected 42 and read 0
Test ts225.tsp.gz
Test tsp225.tsp.gz
Test u1060.tsp.gz
Test u1432.tsp.gz
Test u159.tsp.gz
Test u1817.tsp.gz
Skip test u2152.tsp.gz (too large)
Skip test u2319.tsp.gz (too large)
Test u574.tsp.gz
Test u724.tsp.gz
Test ulysses16.tsp.gz
Test ulysses22.tsp.gz
Skip test usa13509.tsp.gz (too large)
Test vm1084.tsp.gz
Test vm1748.tsp.gz
```

**Comment by jkinable** [comment]
@HannesWell

**Comment by HannesWell** [comment]
In order to get an overview about the current state/functionality of the `TSPLIBImporter` and as requested in #1062 I updated and re-run the following test program to check all TSP instances listed here:
http://comopt.ifi.uni-heidelberg.de/software/TSPLIB95/tsp

Note: the program requires org.apache.commons::commons-compress (version 1.20 used)

```
import org.apache.commons.compress.archivers.*;
import org.apache.commons.compress.archivers.tar.*;
import org.apache.commons.compress.compressors.gzip.*;
import org.jgrapht.*;
import org.jgrapht.graph.*;
import org.jgrapht.nio.tsplib.*;
import org.jgrapht.nio.tsplib.TSPLIBImporter.*;
import org.jgrapht.util.*;

import java.io.*;
import java.net.*;
import java.util.*;
import java.util.Map.*;
import java.util.concurrent.*;
import java.util.function.*;
import java.util.regex.*;
import java.util.stream.*;
import java.util.zip.*;

public class TestAllTSPLibFile
{

    private static final String URL =
        "http://comopt.ifi.uni-heidelberg.de/software/TSPLIB95/tsp/ALL_tsp.tar.gz";

    private static final int MAX_INSTANCE_SIZE = 2000;

    private static final Map<String, Integer> EXPECTED_TOUR_LENGHTS;
    static {
        // optimal lengths according to the specification from
        // http://comopt.ifi.uni-heidelberg.de/software/TSPLIB95/tsp95.pdf
        Map<String, Integer> lengths = new HashMap<>();
        lengths.put("a280", 2579);
        lengths.put("att48", 10628);
        lengths.put("berlin52", 7542);
        lengths.put("ch130", 6110);
        lengths.put("ch150", 6528);
        lengths.put("eil101", 629);
        lengths.put("eil51", 426);
        lengths.put("eil51", 538);
        lengths.put("eil76", 538);
        lengths.put("gr202", 40160);
        lengths.put("gr666", 294358);
        lengths.put("gr96", 55209);
        lengths.put("kroA100", 21282);
        lengths.put("kroC100", 20749);
        lengths.put("kroD100", 21294);
        lengths.put("lin105", 14379);
        lengths.put("pcb442", 50778);
        lengths.put("pr76", 108159);
        lengths.put("st70", 675);
        lengths.put("tsp225", 3919);
        lengths.put("ulysses22", 7013);
        EXPECTED_TOUR_LENGHTS = Map.copyOf(lengths);
    }

    public static void main(String[] args)
        throws IOException
    {
        try (
            InputStream in = new BufferedInputStream(new URL(URL).openStream());
            ArchiveInputStream tar = new TarArchiveInputStream(new GzipCompressorInputStream(in)))
        {
            for (ArchiveEntry entry; (entry = tar.getNextEntry()) != null;) {
                try {
                    readTSPLIBFile(new GZIPInputStream(tar), entry.getName());
                } catch (Exception e) {
                    printError("Failed to load file " + entry.getName() + " : " + e.getMessage());
                }
            }
        }
        if (!NAME_2_PENDING_TOUR_CONTENT.isEmpty()) {
            printError("Pending tours: " + NAME_2_PENDING_TOUR_CONTENT.keySet());
        }
        print("Completed");
    }

    private static final Pattern TSP_FILE_PATTERN = Pattern.compile("([a-zA-Z]+(\\d+))\\.tsp\\.gz");
    private static final Pattern TSP_TOUR_PATTERN =
        Pattern.compile("([a-zA-Z]+(\\d+))\\.opt\\.tour\\.gz");
    private static final int NAME = 1;
    private static final int SIZE = 2;

    private static final Map<String, Graph<String, DefaultWeightedEdge>> NAME_2_GRAPH =
        new ConcurrentHashMap<>();
    private static final Map<String, Metadata<String, DefaultWeightedEdge>> NAME_2_METADATA =
        new ConcurrentHashMap<>();
    private static final Map<String, String> NAME_2_PENDING_TOUR_CONTENT =
        new ConcurrentHashMap<>();

    private static void readTSPLIBFile(InputStream inStream, String fileName)
        throws IOException
    {
        Reader reader = new InputStreamReader(inStream);
        Matcher instanceMatcher = TSP_FILE_PATTERN.matcher(fileName);
        if (instanceMatcher.matches()) {
            String name = instanceMatcher.group(NAME);
            int instanceSize = Integer.parseInt(instanceMatcher.group(SIZE));

            readTSPInstance(reader, name, instanceSize);
        }
        Matcher tourMatcher = TSP_TOUR_PATTERN.matcher(fileName);
        if (tourMatcher.matches()) {
            String name = tourMatcher.group(NAME);
            if (NAME_2_GRAPH.containsKey(name)) {
                readTSPTourFile(reader, name);
            } else {
                // store the tour-file for later load once the graph is loaded
                loadAsPendingTour(reader, name);
            }
        }
    }

    private static void readTSPInstance(Reader reader, String name, int expectedSize)
    {
        if (expectedSize > MAX_INSTANCE_SIZE) {
            print("Skip TSP " + name + " (too large)");
            return;
        }

        Supplier<Integer> intSupplier = SupplierUtil.createIntegerSupplier();
        Supplier<String> vertexSupplier = () -> "v" + intSupplier.get();
        Supplier<DefaultWeightedEdge> edgeSupplier =
            SupplierUtil.createDefaultWeightedEdgeSupplier();
        Graph<String, DefaultWeightedEdge> graph =
            new SimpleDirectedWeightedGraph<>(vertexSupplier, edgeSupplier);
        TSPLIBImporter<String, DefaultWeightedEdge> importer = new TSPLIBImporter<>();
        importer.importGraph(graph, reader);
        Metadata<String, DefaultWeightedEdge> metadata = importer.getMetadata();

        assertSize(name + " - vertexSet", expectedSize, graph.vertexSet().size());
        assertSize(name + " - metadata", expectedSize, metadata.getVertexToNodeMapping().size());

        print("TSP " + name + " loaded and validated successfully");
        GraphPath<String, DefaultWeightedEdge> canonicalTour = getCanonicalTour(graph, metadata);
        print("TSP " + name + " canonical tour length: " + canonicalTour.getWeight());

        NAME_2_GRAPH.put(name, graph);
        NAME_2_METADATA.put(name, metadata);

        String pendingTour = NAME_2_PENDING_TOUR_CONTENT.remove(name);
        if (pendingTour != null) {
            readTSPTourFile(new StringReader(pendingTour), name);
        }
    }

    private static void readTSPTourFile(Reader reader, String name)
    {
        Graph<String, DefaultWeightedEdge> graph = NAME_2_GRAPH.remove(name);
        Metadata<String, DefaultWeightedEdge> metadata = NAME_2_METADATA.remove(name);

        TSPLIBImporter<String, DefaultWeightedEdge> importer = new TSPLIBImporter<>();
        importer.importTour(metadata, reader);
        Metadata<String, DefaultWeightedEdge> tourMetadata = importer.getMetadata();
        GraphPath<String, DefaultWeightedEdge> tour = getTour(graph, tourMetadata.getTour());

        Integer expectedLength = EXPECTED_TOUR_LENGHTS.get(name);
        if (expectedLength == null) {
            throw new IllegalStateException("Expected tour length missing for " + name);
        }
        try {
            assertSize(name + "-tour length", expectedLength, (int) tour.getWeight());
            print("TSP tour " + name + " loaded and validated successfully");
        } catch (Exception e) {
            // don't throw in case this is called from tsp-instance read for a pending tour
            printError(e.getMessage());
        }
    }

    public static <V, E> GraphPath<V, E> getTour(Graph<V, E> graph, List<V> tour)
    {
        tour = new ArrayList<>(tour);
        V startVertex = tour.get(0);
        if (!startVertex.equals(tour.get(tour.size() - 1))) {
            tour.add(startVertex); // close tour
        }

        List<E> edgeList = new GraphWalk<>(graph, tour, 0).getEdgeList();
        long tourLength =
            edgeList.stream().mapToLong(e -> Math.round(graph.getEdgeWeight(e))).sum();
        return new GraphWalk<>(graph, startVertex, startVertex, tour, edgeList, tourLength);
    }

    public static <V,
        E> GraphPath<V, E> getCanonicalTour(Graph<V, E> graph, Metadata<V, E> metadata)
    {
        Map<V, Node> vertexToNode = metadata.getVertexToNodeMapping();
        List<V> vertexList = vertexToNode
            .entrySet().stream().sorted(Comparator.comparingInt(e -> e.getValue().getNumber()))
            .map(Entry::getKey).collect(Collectors.toList());

        for (int i = 0; i < vertexList.size(); i++) {
            if (vertexToNode.get(vertexList.get(i)).getNumber() != i + 1) {
                throw new IllegalArgumentException(
                    "Node numbers of TSP instance are not continuous");
            }
        }

        return getTour(graph, vertexList);
    }

    private static void loadAsPendingTour(Reader reader, String name)
        throws IOException
    {
        StringWriter stringWriter = new StringWriter();
        reader.transferTo(stringWriter);
        String tourContent = stringWriter.getBuffer().toString();
        NAME_2_PENDING_TOUR_CONTENT.put(name, tourContent);
    }

    private static void assertSize(String name, int expectedSize, int actualSize)
    {
        if (actualSize != expectedSize) {
            throw new IllegalStateException(
                name + " expected " + expectedSize + " but read " + actualSize);
        }
    }

    private static void print(Object str)
    {
        System.out.println(str);
    }

    private static void printError(Object str)
    {
        System.err.println(str);
    }
}
```

This program writes the following output:

```
TSP a280 loaded and validated successfully
TSP a280 canonical tour length: 2808.0
TSP tour a280 loaded and validated successfully
TSP ali535 loaded and validated successfully
TSP ali535 canonical tour length: 3367578.0
TSP att48 loaded and validated successfully
TSP att48 canonical tour length: 49840.0
TSP tour att48 loaded and validated successfully
TSP att532 loaded and validated successfully
TSP att532 canonical tour length: 309636.0
Failed to load file bayg29.tsp.gz : bayg29 - vertexSet expected 29 but read 0
Failed to load file bays29.tsp.gz : bays29 - vertexSet expected 29 but read 0
TSP berlin52 loaded and validated successfully
TSP berlin52 canonical tour length: 22205.0
TSP tour berlin52 loaded and validated successfully
TSP bier127 loaded and validated successfully
TSP bier127 canonical tour length: 393989.0
Failed to load file brazil58.tsp.gz : brazil58 - vertexSet expected 58 but read 0
Skip TSP brd14051 (too large)
Failed to load file brg180.tsp.gz : brg180 - vertexSet expected 180 but read 0
TSP burma14 loaded and validated successfully
TSP burma14 canonical tour length: 4659.0
TSP ch130 loaded and validated successfully
TSP ch130 canonical tour length: 47797.0
TSP tour ch130 loaded and validated successfully
TSP ch150 loaded and validated successfully
TSP ch150 canonical tour length: 52814.0
TSP tour ch150 loaded and validated successfully
TSP d1291 loaded and validated successfully
TSP d1291 canonical tour length: 150852.0
Skip TSP d15112 (too large)
TSP d1655 loaded and validated successfully
TSP d1655 canonical tour length: 206087.0
Skip TSP d18512 (too large)
TSP d198 loaded and validated successfully
TSP d198 canonical tour length: 22498.0
Skip TSP d2103 (too large)
TSP d493 loaded and validated successfully
TSP d493 canonical tour length: 113549.0
TSP d657 loaded and validated successfully
TSP d657 canonical tour length: 232159.0
Failed to load file dantzig42.tsp.gz : dantzig42 - vertexSet expected 42 but read 0
TSP dsj1000 loaded and validated successfully
TSP dsj1000 canonical tour length: 5.57634042E8
TSP eil101 loaded and validated successfully
TSP eil101 canonical tour length: 2062.0
TSP tour eil101 loaded and validated successfully
TSP eil51 loaded and validated successfully
TSP eil51 canonical tour length: 1308.0
eil51-tour length expected 538 but read 426
TSP eil76 loaded and validated successfully
TSP eil76 canonical tour length: 1969.0
TSP tour eil76 loaded and validated successfully
TSP fl1400 loaded and validated successfully
TSP fl1400 canonical tour length: 172735.0
TSP fl1577 loaded and validated successfully
TSP fl1577 canonical tour length: 51304.0
Skip TSP fl3795 (too large)
TSP fl417 loaded and validated successfully
TSP fl417 canonical tour length: 55445.0
Skip TSP fnl4461 (too large)
Failed to load file fri26.tsp.gz : fri26 - vertexSet expected 26 but read 0
TSP gil262 loaded and validated successfully
TSP gil262 canonical tour length: 26298.0
Failed to load file gr120.tsp.gz : gr120 - vertexSet expected 120 but read 0
TSP gr137 loaded and validated successfully
TSP gr137 canonical tour length: 97447.0
Failed to load file gr17.tsp.gz : gr17 - vertexSet expected 17 but read 0
TSP gr202 loaded and validated successfully
TSP gr202 canonical tour length: 59538.0
gr202-tour length expected 40160 but read 41567
Failed to load file gr21.tsp.gz : gr21 - vertexSet expected 21 but read 0
TSP gr229 loaded and validated successfully
TSP gr229 canonical tour length: 180258.0
Failed to load file gr24.tsp.gz : gr24 - vertexSet expected 24 but read 0
TSP gr431 loaded and validated successfully
TSP gr431 canonical tour length: 234767.0
Failed to load file gr48.tsp.gz : gr48 - vertexSet expected 48 but read 0
TSP gr666 loaded and validated successfully
TSP gr666 canonical tour length: 425946.0
gr666-tour length expected 294358 but read 296866
TSP gr96 loaded and validated successfully
TSP gr96 canonical tour length: 81317.0
gr96-tour length expected 55209 but read 55489
Failed to load file hk48.tsp.gz : hk48 - vertexSet expected 48 but read 0
TSP kroA100 loaded and validated successfully
TSP kroA100 canonical tour length: 191387.0
TSP tour kroA100 loaded and validated successfully
TSP kroA150 loaded and validated successfully
TSP kroA150 canonical tour length: 287844.0
TSP kroA200 loaded and validated successfully
TSP kroA200 canonical tour length: 373938.0
TSP kroB100 loaded and validated successfully
TSP kroB100 canonical tour length: 157190.0
TSP kroB150 loaded and validated successfully
TSP kroB150 canonical tour length: 273239.0
TSP kroB200 loaded and validated successfully
TSP kroB200 canonical tour length: 327456.0
TSP kroC100 loaded and validated successfully
TSP kroC100 canonical tour length: 183466.0
TSP tour kroC100 loaded and validated successfully
TSP kroD100 loaded and validated successfully
TSP kroD100 canonical tour length: 170990.0
TSP tour kroD100 loaded and validated successfully
TSP kroE100 loaded and validated successfully
TSP kroE100 canonical tour length: 188351.0
TSP lin105 loaded and validated successfully
TSP lin105 canonical tour length: 36480.0
TSP tour lin105 loaded and validated successfully
TSP lin318 loaded and validated successfully
TSP lin318 canonical tour length: 119872.0
TSP linhp318 loaded and validated successfully
TSP linhp318 canonical tour length: 119872.0
TSP nrw1379 loaded and validated successfully
TSP nrw1379 canonical tour length: 712343.0
TSP p654 loaded and validated successfully
TSP p654 canonical tour length: 107737.0
Failed to load file pa561.tsp.gz : pa561 - vertexSet expected 561 but read 0
TSP pcb1173 loaded and validated successfully
TSP pcb1173 canonical tour length: 123837.0
Skip TSP pcb3038 (too large)
TSP pcb442 loaded and validated successfully
TSP pcb442 canonical tour length: 221440.0
TSP tour pcb442 loaded and validated successfully
Skip TSP pla33810 (too large)
Skip TSP pla7397 (too large)
Skip TSP pla85900 (too large)
TSP pr1002 loaded and validated successfully
TSP pr1002 canonical tour length: 349403.0
Failed to load file pr1002.tsp.gz : Failed to import tour from TSPLIB-file: For input string: "1    2    5    3    4    6    7    8    9   10   11   12   63   64   62   61"
TSP pr107 loaded and validated successfully
TSP pr107 canonical tour length: 62752.0
TSP pr124 loaded and validated successfully
TSP pr124 canonical tour length: 98941.0
TSP pr136 loaded and validated successfully
TSP pr136 canonical tour length: 287028.0
TSP pr144 loaded and validated successfully
TSP pr144 canonical tour length: 93526.0
TSP pr152 loaded and validated successfully
TSP pr152 canonical tour length: 160980.0
TSP pr226 loaded and validated successfully
TSP pr226 canonical tour length: 110417.0
Skip TSP pr2392 (too large)
TSP pr264 loaded and validated successfully
TSP pr264 canonical tour length: 77977.0
TSP pr299 loaded and validated successfully
TSP pr299 canonical tour length: 83506.0
TSP pr439 loaded and validated successfully
TSP pr439 canonical tour length: 270646.0
TSP pr76 loaded and validated successfully
TSP pr76 canonical tour length: 150781.0
TSP tour pr76 loaded and validated successfully
TSP rat195 loaded and validated successfully
TSP rat195 canonical tour length: 4030.0
TSP rat575 loaded and validated successfully
TSP rat575 canonical tour length: 12934.0
TSP rat783 loaded and validated successfully
TSP rat783 canonical tour length: 72134.0
TSP rat99 loaded and validated successfully
TSP rat99 canonical tour length: 2124.0
TSP rd100 loaded and validated successfully
TSP rd100 canonical tour length: 50560.0
Failed to load file rd100.tsp.gz : Failed to import tour from TSPLIB-file: For input string: "1  18  62  87  15  63  86  97  67  13"
TSP rd400 loaded and validated successfully
TSP rd400 canonical tour length: 215558.0
Skip TSP rl11849 (too large)
TSP rl1304 loaded and validated successfully
TSP rl1304 canonical tour length: 3231694.0
TSP rl1323 loaded and validated successfully
TSP rl1323 canonical tour length: 3088190.0
TSP rl1889 loaded and validated successfully
TSP rl1889 canonical tour length: 6601280.0
Skip TSP rl5915 (too large)
Skip TSP rl5934 (too large)
Failed to load file si1032.tsp.gz : si1032 - vertexSet expected 1032 but read 0
Failed to load file si175.tsp.gz : si175 - vertexSet expected 175 but read 0
Failed to load file si535.tsp.gz : si535 - vertexSet expected 535 but read 0
TSP st70 loaded and validated successfully
TSP st70 canonical tour length: 3410.0
TSP tour st70 loaded and validated successfully
Failed to load file swiss42.tsp.gz : swiss42 - vertexSet expected 42 but read 0
TSP ts225 loaded and validated successfully
TSP ts225 canonical tour length: 276540.0
TSP tsp225 loaded and validated successfully
TSP tsp225 canonical tour length: 10349.0
tsp225-tour length expected 3919 but read 3916
TSP u1060 loaded and validated successfully
TSP u1060 canonical tour length: 260174.0
TSP u1432 loaded and validated successfully
TSP u1432 canonical tour length: 183070.0
TSP u159 loaded and validated successfully
TSP u159 canonical tour length: 43381.0
TSP u1817 loaded and validated successfully
TSP u1817 canonical tour length: 71460.0
Skip TSP u2152 (too large)
Skip TSP u2319 (too large)
TSP u574 loaded and validated successfully
TSP u574 canonical tour length: 40197.0
TSP u724 loaded and validated successfully
TSP u724 canonical tour length: 157485.0
TSP ulysses16 loaded and validated successfully
TSP ulysses16 canonical tour length: 9693.0
Failed to load file ulysses16.tsp.gz : Failed to import tour from TSPLIB-file: For input string: "1 14 13 12 7 6 15 5 11 9 10 16 3 2 4 8"
TSP ulysses22 loaded and validated successfully
TSP ulysses22 canonical tour length: 12316.0
ulysses22-tour length expected 7013 but read 7117
Skip TSP usa13509 (too large)
TSP vm1084 loaded and validated successfully
TSP vm1084 canonical tour length: 5350742.0
TSP vm1748 loaded and validated successfully
TSP vm1748 canonical tour length: 1.0005342E7
Pending tours: [pr2392, brg180, fri26, gr120, pa561, bays29, gr24, bayg29, gr48]
Completed
```

**Comment by HannesWell** [comment]
This leads to the following list of things that need to be done for the TSPLIBImporter:

- [ ] Implement support for `EDGE_WEIGHT_SECTION` data-parts. At the moment only `NODE_COORD_SECTION` and `TOUR_SECTION` are supported.
- [ ] Besides the three sections above there is  a `DEPOT_SECTION`, `DEMAND_SECTION`, `EDGE_DATA_SECTION`, `FIXED_EDGES_SECTION` and `DISPLAY_DATA_SECTION` contained in the TSPLIB 95 specification. It should be evaluated if these could be of interest for JGraphT and if so they should be handled.
- [ ] Fix the distance function(s) used in `eil51`, `gr666`, `gr96`, `tsp225`, `ulysses22` and `ulysses16`. This is issue #1064
- [ ] Enhance the read of Tour sections so that vertex-lists in row/matrix shape are supported.

Besides fixing the regressions listed above I suggest the following improvements of the API/structure of the `TSPLIBImporter`
(inspired by this TSPLIB-reader https://github.com/coin-or/jorlib/tree/master/jorlib-core/src/main/java/org/jorlib/io/tspLibReader mentioned by @jkinable):
- [ ] make nested classes top-level classes in the `org.jgrapht.nio.tsplib` package (this makes the actual importer shorter and the package is quite empty anyway and makes the classes usable by a possible `TSPLIBExporter`).
- [ ] instead of specifying valid types/format as List of string constants corresponding enum-types should be created. This way the distance functions could be directly implemented into a corresponding `EGDE_WEIGHT_TYPE` literal.
- [ ] MetaData.getTour() should be extended to getTours() (since a file can contain multiple tours) and each tour should be a `GraphPath<V,E>` (with the accumulated length of the tour set as tour-weight) instead of only a `List<V>`.
- [ ] The imported graph should be referenced by the MetaData object for convenience (so graph and tours are bundled in one object because in most cases they are used together anyways), even tough the graph is passed to the importGraph() and therefore known.
- [ ] The class `MetaData` could have a better name like `TSPInstance` or similar.

**Comment by jkinable** [comment]
Thanks @HannesWell, yes the first 4 items targeting the bug fix in the distance computation as well as full support of the TSPLib standard are highly desirable and should be prioritized if possible. I agree that the TSPLib standard ain't exactly the prettiest, especially since there exist a ton of 'minor' deviations within the standard.

I agree with the other suggestions as well. I would use `TSPLibInstance` as opposed to `TSPInstance`, because technically a 2D array would be sufficient to model a `TSPInstance`. It would indeed be a lot cleaner to swap out all the Strings for proper enums.

**Comment by HannesWell** [comment]
Alright, I'll try my best to work on this as soon as possible (Probably not immediately but soon).

Regarding the deviations: Sadly this is true. I think the only solution is to test as many real-world examples as possible and cover the acceptable cases. Do you have more instances you would like to make work? I only the [National TSP of the University of Waterloo](know http://www.math.uwaterloo.ca/tsp/world/countries.html). I used many of them and they worked fine.

I agree that the name `TSPLibInstance` is better.

**Comment by HannesWell** [comment]
The PR #1080 adds support for tours specified in a row and fixes the erroneous distance computation for `EDGE_WEIGHT_TYPE` `GEO`. 
I've updated the `TestAllTSPLibFile` program (added expected lengths for now working tours) and its output in my [previous comment](https://github.com/jgrapht/jgrapht/issues/1067#issuecomment-812866043).

The following points have changed:
- tours defined by lists defined as a row are read correctly
- The tours of the TSP-instance `gr666`, `gr96`, `ulysses22` and `ulysses16` (all with `EDGE_WEIGHT_TYPE` `GEO` are read correctly)
- Load of `ali535.tsp` now fails because of point 501 which is defined the following way: `501  40.62  13.11`
But since in type GEO the decimal part of each coordinate represents minutes of arc (so 60th of a degree) the decimal part must not be greater than `0.60` respectively not smaller than `-0.60`.
- The canonical tour lengths read by the `TSPLibImporter` for `pcb442`, `gr666`, and `att532` now match lengths given in section `2.7 Verification` of the TSPLIB specification.

From all tours that can be checked at the moment only those for `eil51` and `tsp225` have a different length than given in the TSPLIB specification. Both have EDGE_WEIGHT_TYPE EUC_2D. I will continue to search for the cause but I also think that the values given in the TSPLIB specification could be wrong.
